### ISSUE TITLE
Flow support

### ISSUE THREAD

**Issue by sobolevn** [znck/prop-types#1]
Hi, this library looks interesting!

I am using `flow` to get type hints, is it supported?
Here's the full setup just for the reference: https://github.com/wemake-services/wemake-vue-template

Thanks!

**Comment by znck** [comment]
Typescript types are there. I have to check how to provide flow support.

**Comment by znck** [comment]
I hope this is suffice.
https://github.com/znck/prop-types/blob/a25d220b899662d96a46d69b391a2fdb028c2dfb/types/index.js.flow#L1-L38

Please test it with flow.

**Comment by sobolevn** [comment]
I will test it shortly. Thanks!
