### ISSUE TITLE
Usage of lodash-es results in SyntaxError

### ISSUE THREAD

**Issue by faroutchris** [znck/prop-types#5]
Hey,
I'm trying to use this package but the dependency to lodash-es makes it impossible.

Since it's using ES modules, it's not able to run on node v8.9.4. This is the error message I'm receiving:

```
../node_modules/lodash-es/lodash.js:10
export { default as add } from './add.js';
^^^^^^

SyntaxError: Unexpected token export
```

Any ideas on how to resolve this?

**Comment by faroutchris** [comment]
I've created a PR #6 which resolves my issue. 

I don't know if there's a better way, but these changes make it possible to use this package for server-rendered Vue components.

**Comment by znck** [comment]
Removed lodash dependency.
